### ISSUE TITLE
xmldom dependency has a security issue

### ISSUE THREAD

**Issue by karfau** [xeokit/xeokit-convert#10]
Latest versions of the `xmldom` lib are now only published as `@xmldom/xmldom`, so to update from version 0.6.0 [which is known to be vulnerable](https://github.com/xmldom/xmldom/security/advisories/GHSA-5fg8-2547-mr8q), it's required to switch to the scoped package. For more details see https://github.com/xmldom/xmldom/issues/271

I'm one of the maintainers and I can provide an update PR if you want.

**Comment by AkechiShiro** [comment]
Hey @xeolabs, would you be willing to update this dependency ? Or accept the PR of @karfau  ?
I don't know if this has been held off as it could have been a breaking change or something like that.

Here is what the tool `snyk` says when testing `@xeokit/xeokit-convert`.
```
Testing @xeokit/xeokit-convert...

✗ Medium severity vulnerability found in xmldom
  Description: Improper Input Validation
  Info: https://snyk.io/vuln/SNYK-JS-XMLDOM-1534562
  Introduced through: xmldom@0.6.0
  From: xmldom@0.6.0



Organization:      akechishiro
Package manager:   npm
Open source:       yes
Project path:      @xeokit/xeokit-convert

Tested @xeokit/xeokit-convert for known vulnerabilities, found 1 vulnerability, 1 vulnerable path.
```

**Comment by xeolabs** [comment]
Thanks @karfau 
@AkechiShiro - I've bumped xmldom to 0.8.2 and published @xeokit/xeokit-convert 1.0.8-beta-7 with this update.

**Comment by AkechiShiro** [comment]
Thanks for your quick response @xeolabs, would you have any idea how much time it will take for the new beta release to be seen by NPM ? Maybe a day or two ? If I want to install the new beta release, how should I proceed ?

**Comment by AkechiShiro** [comment]
Thanks for the update, wasn't aware that was a possible issue with npm.
Maybe they received lots of update in little time, the new release may be added in a hour or so I guess.

**Comment by AkechiShiro** [comment]
Looks like it's finally out !
