### ISSUE TITLE
convert2xkt.js TypeError: fetch failed

### ISSUE THREAD

**Issue by FedeIneco** [xeokit/xeokit-convert#101]
![Captura de pantalla 2023-02-28 123043](https://user-images.githubusercontent.com/126453386/221841344-19119eb1-26cd-4249-8bd2-50b15111c814.png)

Hi,
I'm trying to convert an IFC file into XKT using convert2xkt.js script. When I use it,  it drops me this error.
I also tried to use the function and it dropped this one.

![Captura de pantalla 2023-02-28 124013](https://user-images.githubusercontent.com/126453386/221843381-ae824cb7-3888-426b-8245-05bc177a9678.png)

This is the code

![image](https://user-images.githubusercontent.com/126453386/221843543-79baa39a-2a3a-4050-8cf6-170844e98bda.png)

**Comment by assaad977** [comment]
if you have Node 17+, you will need to add --no-experimental-fetch flag

**Comment by FedeIneco** [comment]
> si tiene Node 17+, deberá agregar el indicador --no-experimental-fetch

It drops me this msg:
error: unknown option '--no-experimental-fetch'

**Comment by FedeIneco** [comment]
> > > > si tiene Node 17+, deberá agregar el indicador --no-experimental-fetch
> > > 
> > > 
> > > It drops me this msg: error: unknown option '--no-experimental-fetch'
> > 
> > 
> > can you verify what node version do you have ?
> 
> 18.14.0

oh, I was making a mistake in the flag's placement. Thank you!
