### ISSUE TITLE
Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by Trigger93** [xeokit/xeokit-convert#102]
Hello,

is there any possibilty to solve this problem?

Error:
[convert2xkt] Running convert2xkt v1.1.7...
[convert2xkt] Reading input file: xyz
[convert2xkt] Input file size: 580692.74 kB
[convert2xkt] Using parser: parseIFCIntoXKTModel
Error: TypeError: fetch failed

**Comment by Trigger93** [comment]
https://github.com/xeokit/xeokit-convert/issues/101#issuecomment-1481367225

**Comment by xeolabs** [comment]
This seems like more of a NodeJS issue (re. --no-experimental-fetch) than a xeokit issue - I 'm not sure there is anything broken in xeokit that's causing this issue.

Also it seems that #101 provides a workaround, unless I'm missing something.
