### ISSUE TITLE
.step files to convert 

### ISSUE THREAD

**Issue by Jongonzale** [xeokit/xeokit-convert#108]
It'd be great to have the possibility to convert .step/.stp files to .xkt . It's an ISO Standard format and a lot of different apps of 3d design work with it.
I think that this doesn't work because when I try to convert those files the next error appears 'Error: Error: unsupported source format: "step"'
If someone knows a way to convert this it'd be good to know

**Comment by Amoki** [comment]
You can convert step to glTF with online tools or libraries in many languages then convert glTF to xkt.

**Comment by xeolabs** [comment]
Did you check the tutorials? Lots of info on there on converting STEP files to XKT: https://www.notion.so/xeokit/xeokit-Documentation-4598591fcedb4889bf8896750651f74e
