### ISSUE TITLE
 How to convert an ifc file into an xkt model

### ISSUE THREAD

**Issue by JianJD** [xeokit/xeokit-convert#115]
I want to convert the ifc file into an xkt model, but I don't know where to download the ifc2gltf package. Can you provide the download address. I am a new student. Can you help me write a complete demo for me to learn

**Comment by xeolabs** [comment]
Hi `ifc2gltf` is a proprietary  tool from Creoox - please [contact Creoox here](https://creoox.com/en/contact/) for info.

**Comment by JianJD** [comment]
I can't find this download button. Do you need to submit your contact information? If you know if the download button can provide an exact URL

**Comment by xeolabs** [comment]
Yes you need to submit your contact information, there is not download link.

**Comment by xeolabs** [comment]
Note that there is also "community" conversion pipeline as well - ifc2gltf is aimed more at commercial users - perhaps this fits your needed better: https://www.notion.so/xeokit/Converting-IFC-Models-to-XKT-using-Open-Source-Tools-A-Simpler-Pipeline-02d45ba457eb4f808f63bcacb71a4fb3
