### ISSUE TITLE
Add convert2xkt.conf.js to package.json files

### ISSUE THREAD

**Issue by OscarArranzModelical** [xeokit/xeokit-convert#123]
Hi! We made some changes to a software that uses xeokit-convert and when we built and executed the docker container we got an error saying that `convert2xkt.conf.js` can't be resolved.

We could successfully fix the issue by rolling back to v1.1.12 but I did a bit of investigation and found out that the distributed files are lacking at least this new file called `convert2xkt.conf.js`. I'm guessing there's something wrong with the rollup config but I am not familiar with rollup so I don't know exactly what it could be.

The beta version that was installed is [1.1.15-beta](https://www.npmjs.com/package/@xeokit/xeokit-convert/v/1.1.15-beta), I leave this as reference in case someone sees this issue in the future and it doesn't apply anymore.

**Comment by xeolabs** [comment]
Hi, yes I added that last week. I will add `convert2xkt.conf.js` to the `package.json` later today. It is a set of bundled configurations for the various rendering modes, as an external configs file because we're running out of space on the command line for new args.

**Comment by OscarArranzModelical** [comment]
> command

Great! I had just toyed a bit with the repo and found that the file `convert2xkt.conf.js` was missing from the `files` property, I was going to send a PR with the fix but if you already did then that's great!

Thanks for the quick response!

**Comment by xeolabs** [comment]
No probs - hold off until tomorrow until integrating the latest though, tonight we need to run the test suite over it first, before publishing a build.

**Comment by xeolabs** [comment]
Ready now, see latest build
