### ISSUE TITLE
IFC to XKT has evaluation version

### ISSUE THREAD

**Issue by kushal154** [xeokit/xeokit-convert#163]
I  am getting the evaluation version as part of the final xkt file after using ifc2gltf and xeokit-convert. I'm sharing the screenshot for reference <img width="1538" alt="Screenshot 2024-07-07 at 8 47 24 AM" src="https://github.com/xeokit/xeokit-convert/assets/3103087/8f3b3a75-bb08-427a-8552-da22ec41abbc">. 

How do I get rid of it?

**Comment by xeolabs** [comment]
Please contact Creoox for a token key, that you can insert into the configuration file for `ifc2gltcxconverter`. This watermark is created by `ifc2gltcxconverter` as long as that token is absent.
