### ISSUE TITLE
Fatal JavaScript invalid size error 169220804 when converting to xkt large ifc model

### ISSUE THREAD

**Issue by ebs123** [xeokit/xeokit-convert#173]
Hi.

I trying to convert large ifc model (about 350 mb), and after converting, when process is going to "Writing to XKT file...", I got error "Fatal JavaScript invalid size error 169220804". Snapshot at attachments.
![snapshot](https://github.com/user-attachments/assets/123ba78c-44f0-4c85-9a5e-a53c6b52b6a1)

**Comment by xeolabs** [comment]
Usually this is a limitation with the 3rd-party web-ifc library that we use for direct IFC->XKT conversion. 

We plan to build a warning into convert2xkt for this case.

For large IFC files, we recommend using the conversion tools described [on this page](https://xeokit.github.io/xeokit-model-conversion-tests/ifc-tests.html).

Contact us [here](https://xeokit.io/for-business) if you'd like to evaluate this option.
