### ISSUE TITLE
How can I convert a IFC file to XKT with a MetaModel JSON?

### ISSUE THREAD

**Issue by lanjoni** [xeokit/xeokit-convert#44]
How can I convert a IFC file to XKT with a MetaModel JSON? This is a little problem...

**Comment by baoxiaozhi** [comment]
Have you solved this problem? I have the same problem as you.

**Comment by lanjoni** [comment]
> Have you solved this problem? I have the same problem as you.

Yes! Using the conversion method in the "bimspot" repository! The process is a little longer, but it gives a higher performance. 
Link: https://github.com/bimspot/xeokit-converter
