### ISSUE TITLE
Any release 1.0.8 planned soon ?

### ISSUE THREAD

**Issue by AkechiShiro** [xeokit/xeokit-convert#46]
Hi @xeolabs,

I'm wondering if a stable release is coming up soon, as multiples dependencies have been bumped and some due to security issues. I know that this is an open source project and as such I'm not really asking for a very precise ETA, but could this come in a month or ? Maybe few months or weeks ?

**Comment by xeolabs** [comment]
Hi, here's a stable release: @xeokit/xeokit-convert@1.0.9
