### ISSUE TITLE
Problems consolidating packages

### ISSUE THREAD

**Issue by tbmmarques** [xeokit/xeokit-convert#51]
> When I started testing, we had problems restoring packages. I emphasize here the caution for the release and warnings about possible related problems.

### **Test 1:**

Installing with `npm i @xeokit/xeokit-convert`
>  Breakage when bringing package

### **Test 2:**

Cloning Release

> Missing files like _convert2xkt.js_

### **Test 3:**

Download the Release in _ZIP format_
At the time of restoring the package, some dependencies are discontinued and with errors in the download. The packages are:
> puppeteer-firefox
> @percy/script

![image](https://user-images.githubusercontent.com/63127488/171467472-c540827b-38fd-47a1-ae9a-5f22068f8c20.png)

**Another point of care is the versions of dependencies, although xeokit-convert was released at the end of April, we still have some packages that have become obsolete.**
> 
> Package                     Avalible        Latest  
> @loaders.gl/core        3.0.13         3.2.3                         
> @loaders.gl/json        3.0.13         3.2.3                        
> @loaders.gl/las          3.0.13          3.2.3                         
> @loaders.gl/obj         3.2.3            3.2.3                         
> @loaders.gl/ply          3.2.3           3.2.3                         
> @loaders.gl/polyfills   3.2.3           3.2.3                         
> @zip.js/zip.js               2.2.38         2.4.12   
> autoprefixer:               9.8.5           10.4.7                     
> earcut                          2.2.2           2.2.3           
> jszip                            3.6.0           3.10.0                     
> puppeteer                  10.4.0          14.1.2  
> request                       2.79.0          2.88.2                         
> web-ifc                       0.0.30          0.0.35                         
> xmldom                      0.6.0           0.6.0                         
> rollup                          2.46.0         2.75.5
> rollup-plugin-commonjs 10.1.0    22.0.0
> rollup-plugin-node-resolve 5.2.0  13.3.0

### **Terminal**

> `PS D:\Downloads\xeokit-convert-1.0.7> npm update
> npm WARN deprecated @percy/script@1.1.0: PercyScript has been deprecated in favor of Percy CLI's snapshot command: https://docs.percy.io/docs/percy-snapshot Please upgrade to use the CLI rather than this package, as it's no longer actively supported.
> npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
> npm WARN deprecated jssha@2.4.2: jsSHA versions < 3.0.0 will no longer receive feature updates
> npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
> npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.      
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
> npm WARN deprecated ecstatic@3.3.2: This package is unmaintained and deprecated. See the GH Issue 259.
> npm WARN deprecated puppeteer-firefox@0.5.1: Firefox support is gradually transitioning to the puppeteer package. As of puppeteer v2.1.0 you can interact with Firefox Nightly. The puppeteer-firefox package will remain available until the transition is complete, but it is no longer actively maintained. For more information visit https://wiki.mozilla.org/Remote
> npm WARN deprecated cli-ux@5.6.6: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
> npm WARN deprecated @percy/agent@0.28.7: @percy/agent is no longer supported. Please upgrade to @percy/cli https://docs.percy.io/docs/migrating-to-percy-cli
> npm WARN deprecated core-js@2.3.0: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm ERR! code 1
> npm ERR! path D:\Downloads\xeokit-convert-1.0.7\node_modules\puppeteer-firefox
> npm ERR! command failed
> npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
> npm ERR! ERROR: Failed to download Firefox rv0.0.1!
> npm ERR! Error: Download failed: server returned code 404. URL: https://github.com/puppeteer/juggler/releases/download/v0.0.1/firefox-win64.zip
> npm ERR!     at D:\Downloads\xeokit-convert-1.0.7\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:264:21
> npm ERR!     at ClientRequest.requestCallback (D:\Downloads\xeokit-convert-1.0.7\node_modules\puppeteer-firefox\lib\BrowserFetcher.js:320:7)
> npm ERR!     at Object.onceWrapper (node:events:642:26)
> npm ERR!     at ClientRequest.emit (node:events:527:28)
> npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:631:27)
> npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
> npm ERR!     at TLSSocket.socketOnData (node:_http_client:494:22)
> npm ERR!     at TLSSocket.emit (node:events:527:28)
> npm ERR!     at addChunk (node:internal/streams/readable:315:12)
> npm ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
> npm ERR!   -- ASYNC --
> npm ERR!     at BrowserFetcher.<anonymous> (D:\Downloads\xeokit-convert-1.0.7\node_modules\puppeteer-firefox\lib\helper.js:32:15)
> npm ERR!     at Object.<anonymous> (D:\Downloads\xeokit-convert-1.0.7\node_modules\puppeteer-firefox\install.js:47:16)
> npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1105:14)
> npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
> npm ERR!     at Module.load (node:internal/modules/cjs/loader:981:32)
> npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
> npm ERR!     at node:internal/main/run_main_module:17:47
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\thiago.marques\AppData\Local\npm-cache\_logs\2022-06-01T17_28_25_233Z-debug-0.log`
>

**Comment by xeolabs** [comment]
#Test 1: 

Installs OK for me, on Ubuntu 20.04.4 LTS, using NodeJS v16.10.0:

````bash
npm i @xeokit/xeokit-convert
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 490 packages, and audited 514 packages in 24s

47 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
````

# Test 2: 

Works for me - perhaps you need to run ````npm install````?

Cloning:

````bash
lindsay@bodacious:/tmp$ git clone https://github.com/xeokit/xeokit-convert.git
Cloning into 'xeokit-convert'...
remote: Enumerating objects: 1807, done.
remote: Counting objects: 100% (264/264), done.
remote: Compressing objects: 100% (123/123), done.
remote: Total 1807 (delta 165), reused 204 (delta 140), pack-reused 1543
Receiving objects: 100% (1807/1807), 243.70 MiB | 6.78 MiB/s, done.
Resolving deltas: 100% (1037/1037), done.
Updating files: 100% (385/385), done.
````
Installing:

````bash
lindsay@bodacious:/tmp$ cd xeokit-convert

lindsay@bodacious:/tmp$ npm install
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated libnpmconfig@1.2.1: This module is not used anymore. npm config is parsed by npm itself and by @npmcli/config
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 704 packages, and audited 705 packages in 2m

56 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (9 high, 1 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
````

Running convert2xkt:

````bash
lindsay@bodacious:/tmp/xeokit-convert$ chmod +x convert2xkt.js 
lindsay@bodacious:/tmp/xeokit-convert$ node convert2xkt.js 
Error: please specify source file path.
Usage: convert2xkt [options]

Options:
  -v, --version               output the version number
  -s, --source [file]         path to source file
  -f, --format [string]       source file format (optional); supported formats are gltf, ifc, laz, las, pcd, ply, stl and
                              cityjson
  -m, --metamodel [file]      path to source metamodel JSON file (optional)
  -i, --include [types]       only convert these types (optional)
  -x, --exclude [types]       never convert these types (optional)
  -r, --rotatex               rotate model 90 degrees about X axis (for las and cityjson)
  -g, --disablegeoreuse       disable geometry reuse (for ifc and gltf)
  -t, --mintilesize [number]  minimum diagonal tile size (optional, default 1000)
  -o, --output [file]         path to target .xkt file; creates directories on path automatically if not existing
  -l, --log                   enable logging
  -h, --help                  display help for command


XKT version: 9
````

# Test 3

I've removed Percy from the build - so you shouldn't be getting these warnings any more.

**Comment by tbmmarques** [comment]
I was able to use **Test 2**.

A warning appeared that there are nine high problems when installing packages.

thanks.
