### ISSUE TITLE
Why is collada used as an intermediary format when IfcConvert can go directly to gltf/glb?

### ISSUE THREAD

**Issue by Moult** [xeokit/xeokit-convert#54]

**Comment by Amoki** [comment]
We've been using IfcConvert t-> glb and glb -> xkt for many years, and I can confirm it works well.

**Comment by Moult** [comment]
@Amoki awesome! So does that mean that these instructions are outdated? https://www.notion.so/Converting-IFC-Models-to-XKT-using-3rd-Party-Open-Source-Tools-c373e48bc4094ff5b6e5c5700ff580ee would you know where the latest instructions are?

**Comment by xeolabs** [comment]
@Moult those instructions are not outdated - we just have three sets of tools for conversion:

1. [Converting IFC Models to XKT using 3rd-Party Open Source Tools](https://www.notion.so/xeokit/Converting-IFC-Models-to-XKT-using-3rd-Party-Open-Source-Tools-c373e48bc4094ff5b6e5c5700ff580ee) - converts IFC->DAE using IfcConvert, DAE->glTF using COLLADA2GLTF, glTF->XKT using convert2xkt. Converts IFC->JSON metadata using xeokit-metadata from BIMSpot. Does not support property sets
2. [Converting Models to XKT with convert2xkt](https://www.notion.so/xeokit/Converting-Models-to-XKT-with-convert2xkt-fa567843313f4db8a7d6535e76da9380) - Direct convert of IFC to XKT, including property sets and metadata
3. [Converting IFC Models to XKT using IFC2glTFCxConverter](https://github.com/a2e0005d00dc4f22b648f1237bc3245d) - supports property sets - this pipeline uses a closed source tool from Creoox, to convert IFC->glTF and metadata JSON, with property sets. Then we use convert2xkt to convert glTF and metadata to XKT

**Comment by Moult** [comment]
That makes sense, I was referring to @Amoki 's suggestion that for option 1, instead of IFC->DAE->glTF->XKT, can't you just go directly IFC->glTF->XKT instead and skip the DAE step?

**Comment by Moult** [comment]
I understand, but if option 1 is still going to be relevant in the future, and if @Amoki  says it works without going through DAE, can option 1 be simplified to skip DAE? One less command, one less dependency?

**Comment by xeolabs** [comment]
Actually @Moult I've not tried the ````IfcConvert``` option to output glTF/glb yet. 

I'll try that today - if that works OK, it would indded allow us to skip the intermediate DAE. Plus, the next release of xeokit's ````convert2xkt```` tool supports glb (with textures) :)

**Comment by xeolabs** [comment]
@Moult I can confirm that we'll very soon be able to convert IFC->XKT without the intermediate DAE.

Once I've merged https://github.com/xeokit/xeokit-convert/pull/50, xeokit-convert will be able to convert .glb.

I also confirmed that IfcConvert is able to convert my test models to .glb, which I was then able to convert to XKT (v10) using that xeokit-convert branch.

So our open source tools for geometry conversion would then be 

IFC->(IfcConvert)->GLB->(convert2xkt)->XKT

And for metadata:

IFC->(xeokit-metadata)->JSON->(convert2xkt)->XKT

This one made it through unscathed, so gratifying:

![Screenshot from 2022-06-08 11-31-19](https://user-images.githubusercontent.com/83100/172583683-4012ff97-4841-491f-8ffd-f97e1e064e41.png)

**Comment by Moult** [comment]
Fantastic! This would be a great step in simplifying the workflow. Feel free to close this bug when its available :)

**Comment by xeolabs** [comment]
Still in alpha/beta, but now released in some alpha/beta packages, with this tutorial:

https://www.notion.so/xeokit/Converting-IFC-Models-to-XKT-using-Open-Source-Tools-A-Simpler-Pipeline-02d45ba457eb4f808f63bcacb71a4fb3

@xeokit/xeokit-sdk 2.3.0-beta-15
@xeokit/xeokit-convert 1.1.0-alpha-3

At this point I just need to nail down a rendering issue with particular models on Firefox. Works great on Chrome though.
