### ISSUE TITLE
Geometry coordinates seem off

### ISSUE THREAD

**Issue by Moult** [xeokit/xeokit-convert#55]
I'm following the steps here: https://www.notion.so/Converting-IFC-Models-to-XKT-using-3rd-Party-Open-Source-Tools-c373e48bc4094ff5b6e5c5700ff580ee

The steps all worked without any errors however the coordinates when viewed in the bim-viewer website seem a little off. My models have large coordinates (e.g. ~6,000,000,000mm and ~300,000,000mm in Sydney, Australia)

Shown in this screenshot are pipes and pipe fittings and as you can see they don't line up.

![2022-06-06-125504_497x661_scrot](https://user-images.githubusercontent.com/88302/172087573-9be39b59-94b9-48d6-8b47-2274f378c2f4.png)

Thoughts?

**Comment by xeolabs** [comment]
@Moult yip we're on it: https://github.com/xeokit/xeokit-convert/issues/63

We just need to tune some arithmetic to compensate for loss of accuracy at higher float values.

**Comment by xeolabs** [comment]
@Moult if you like, you could attach or send the IFC file in question, and I'll include that in my tests.

**Comment by Moult** [comment]
@xeolabs that file unfortunately is part of a client project so I can't share it, but does this file replicate the issue? If so feel free to use it :) https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.7.0/src/blenderbim/test/files/auto-geolocation.ifc

**Comment by xeolabs** [comment]
@Moult should be fixed now by https://github.com/xeokit/xeokit-convert/issues/63
