### ISSUE TITLE
Texture demo doesn't work on Firefox

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-convert#57]
There are a lot of invisible objects in Firefox (works well on Chrome).
![image](https://user-images.githubusercontent.com/1349751/173025156-665cde2c-2956-433b-973c-2cbbce13c361.png)

We still can guess the objects with the Ambient Occlusion
![image](https://user-images.githubusercontent.com/1349751/173027269-a63e6149-ab3c-46d4-96d5-8d7565b4d005.png)

**Comment by xeolabs** [comment]
More context:

![Screenshot from 2022-06-10 11-18-21](https://user-images.githubusercontent.com/83100/173034222-aca7c3ee-9767-4398-bd24-eb2b00fc330b.png)

**Comment by xeolabs** [comment]
Fixed: https://xeokit.github.io/xeokit-sdk/examples/#loading_XKT_HousePlan
