### ISSUE TITLE
Updating web-ifc version to 0.0.35

### ISSUE THREAD

**Issue by tomerel22** [xeokit/xeokit-convert#65]
Hi! Willing to offer $ 25 to solve the problem!
 In the new version of web-ifc version they have fixed this crucial issue [link here](https://github.com/tomvandig/web-ifc/issues/144).
This solution helps to display every ifc file, even if he has a problem in his writing. I just want to solve this issue when I convert my ifc files: 
web-ifc: 0.0.34 threading: 0
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
unexpected placement type
unexpected mesh type
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
non-empty segments in IFCINDEXEDPOLYCURVE currently not supported
XKTEntity has no meshes - won't create: 00tMo7QcxqWdIGvc4sMN2A
XKTEntity has no meshes - won't create: 1BHMk4YA16q9lPAQz_6kce
XKTEntity has no meshes - won't create: 3GgJOmHfz5cO7llCSDSgWw
XKTEntity has no meshes - won't create: 2JsySylQf5JBS80J4RqcyD
XKTEntity has no meshes - won't create: 0hbmG3vtb4_hAsfM74pHDc
XKTEntity has no meshes - won't create: 3iVqqThtf5P9yENvqqyp6l
XKTEntity has no meshes - won't create: 1rhcW0Wbz92RGD4I6F82Yd

I'm attaching my file for an example (with the txt extension, remove it :) ), if it can be display with his walls in the xeokit viewer it will be amazing! Thanks!
[building1.ifc.txt](https://github.com/xeokit/xeokit-convert/files/9128548/building1.ifc.txt)

**Comment by xeolabs** [comment]
Done! Thanks for the heads-up :pray: - updated now in @xeokit/xeokit-convert 1.1.0-alpha-8
