### ISSUE TITLE
Convert script error: glTF Unknown version

### ISSUE THREAD

**Issue by jenbuzz** [xeokit/xeokit-convert#71]
After the latest update v1.1.0 I get this error when running the convert2xkt.js script. I don't see any changes in the documentation/readme related to this. Hence not really sure if I'm using the script wrong now or something broke in latest release. Notice that the same process works with previous (non-alpha) versions.

$ convert2xkt -s "/tmp/test.gltf" -o "/tmp/test.xkt" -l
[convert2xkt] Running convert2xkt v1.1.0...
[convert2xkt] Reading input file: /tmp/test.gltf
[convert2xkt] Input file size: 397.16 kB
glTF: Unknown version -i
Error: Error: 'baseUri' must be provided to resolve relative url test0.bin

**Comment by xeolabs** [comment]
In my experience, that error is thrown by the loaders.gl dependency, which does the actual glTF parsing, when it finds that the glTF JSON does not have a ````version```` property, example below. Does your glTF file have a correct ````version```` property? Should have the value ````2````. 

In any case, would be good for us to wrap that exception in a better message.

See the Box.gltf demo model for reference below:

````json
{
  "asset": {
    "generator": "COLLADA2GLTF",
    "version": "2.0"
  },
  "scene": 0,
  "scenes": [
    {
      "nodes": [
        0
      ]
    }
  ],
  "nodes": [
````

**Comment by jenbuzz** [comment]
Thanks for your reply @xeolabs - you are correct about the wrongly formatted version property. Apparently that didn't matter before but does now. That fixed the first part of my error. Thanks again.

Second part of error is still there:

Error: Error: 'baseUri' must be provided to resolve relative url test0.bin

Where can I define the baseUri? I haven't defined that before and it just worked. Maybe before the latest version the bin file was just assumed to be in the same directory as the gltf file but now it needs to be specified somehow?

**Comment by xeolabs** [comment]
> Error: Error: 'baseUri' must be provided to resolve relative url test0.bin

Yeah that one sounds like an error, since it should be deriving the baseUri from the ````s```` argument. Could you raise that as a new issue? Then you can track that one for the next patch release. Thanks

**Comment by jenbuzz** [comment]
Done. #73 Thanks!
