### ISSUE TITLE
How can I get the metadata.json of ifc  when I convert ifc to xkt??

### ISSUE THREAD

**Issue by baoxiaozhi** [xeokit/xeokit-convert#77]
Can I get the metadata in the process of converting the ifc to XKT ?

**Comment by xeolabs** [comment]
Hi, the latest version of convert2xkt creates XKT v10, which now embeds the JSON metadata within the XKT file.
More info: https://www.notion.so/xeokit/Converting-IFC-Models-to-XKT-using-Open-Source-Tools-A-Simpler-Pipeline-02d45ba457eb4f808f63bcacb71a4fb3
