### ISSUE TITLE
Fix IFC geometry distortion with web-ifc 0.0.35+

### ISSUE THREAD

**Issue by pbbr** [xeokit/xeokit-convert#87]
With the use of web-ifc 0.0.35 and higher, in some models there is a shift of positions of some elements (see example pictures attached). The geometry itself is correct. This doesn't happen with the WebIFCLoaderPlugin (https://xeokit.github.io/xeokit-sdk/docs/class/src/plugins/WebIFCLoaderPlugin/WebIFCLoaderPlugin.js~WebIFCLoaderPlugin.html) as well as web-ifc-viewer. As we saw, the vertex data from web-ifc have changed with version 0.0.35, so the following line gets different positions than with 0.0.34:

`const vertexData = ctx.ifcAPI.GetVertexArray(geometry.GetVertexData(), geometry.GetVertexDataSize());`

Any ideas how the solve this? Is there a missing transformation of the positions after reading from IFC before creating the geometry / meshes?

Thanks for your feedback!

**web-ifc-viewer:**
![image](https://user-images.githubusercontent.com/79220314/206697716-d649c71c-7222-4049-a18c-8206cd11f6ce.png)

**xeokit-convert:**
![image](https://user-images.githubusercontent.com/79220314/206697802-6fc59a3d-0683-44c3-9fb7-932966f17497.png)

**Comment by pbbr** [comment]
@xeolabs Do you have any hint for us to solve this problem?

**Comment by pbbr** [comment]
Problem solved! The issue occurs because of the conversion of the `placedGeometry.flatTransformation` to a Float32Array, where some precision is lost for models which have large distances between objects or objects or geo referenced models. If we remove the array conversion, it works well.

**Comment by pbbr** [comment]
@xeolabs Could you please check and change this in code? Thanks!

**Comment by xeolabs** [comment]
@pbbr Looks good, thanks! I've just published this fix in @xeokit/xeokit-convert@1.1.6

**Comment by pbbr** [comment]
Perfect, thanks!
