### ISSUE TITLE
Node script convert2xkt issue with options

### ISSUE THREAD

**Issue by jenbuzz** [xeokit/xeokit-convert#9]
I have this issue with node script convert2xkt.js where the options where not recognised (e.g. I set "-s filename" and script acts as if it's not set).

In convert2xkt.js we access the options through "program." (e.g. program.source) and that doesn't work. I changed that to "options.source" and all the other "program.xxx" to "options.xxx" too, and now it works.

Funny thing is that is works as it is on windows but it didn't work on ubuntu. I would still suggest changing it to "options." instead of "program." as in the commander docs.

Seems like it's a bug or maybe I am doing something wrong?

**Comment by xeolabs** [comment]
Good catch, thanks! 

Now fixed in @xeokit/xeokit-convert 1.0.1

https://github.com/xeokit/xeokit-convert/commit/80eeb416521f62de42e5e3f080e484381b09ff23
